tags and tracks are in use
wpa11yday/conference pull request #56
Opened 2024-03-20 21:08 UTC by alishanvr

## Description

We introduced two new functions for getting tags and track name as per our requirement mentioned in #55

2024-03-28 19:12 UTC, joedolson requested changes
Overall, it looks good; some semantic and text changes I'd like to see, though.

2024-03-28 19:12 UTC, joedolson commented on src/assets/css/wp-conference-schedule-pro.css
> +        flex-wrap: wrap !important;
Let's avoid using !important unless it's absolutely necessary. This should be manageable by ordering the rules appropriately.

2024-03-28 19:12 UTC, joedolson commented on src/inc/schedule-output-functions.php
> + * @param string $tag_heading_txt Heading text for tags.
This parameter isn't used in the function; either incorporate in the function or remove doc.

2024-03-28 19:12 UTC, joedolson commented on src/inc/schedule-output-functions.php
> +				$filtered_tags_html .= '<span class="talk-tag-wrapper">';
Let's use `ul` and `li` for the tags semantics, so that we have some meaningful structure in the code.

2024-03-28 19:12 UTC, joedolson commented on src/inc/schedule-output-functions.php
> +	$tag_heading_txt = __( 'Tags', 'wpad' );
Let's use 'Topics' as the heading for now.

2024-03-28 19:12 UTC, joedolson commented on src/inc/schedule-output-functions.php
> +		$track_name_html = '<h2 class="talk-track">' . $track_name . '</h2>';
This should not be an `h2` heading.  Let's move the text so it's after the talk title, and link it to the archive page for the track, with no heading. Give it a prefix like "Level:". 

The archive page probably doesn't have any design; we haven't used it previously, but that's something we can work on separately.

2024-03-28 19:12 UTC, joedolson commented on src/inc/schedule-output-functions.php
> +                <h4>$tag_heading_txt</h4>
This should be an `h3`

2024-04-02 19:37 UTC, alishanvr commented
> Overall, it looks good; some semantic and text changes I'd like to see, though.

Hi @joedolson,

Thank you for reviewing it. I have a plan to fix all these during the [Eid Al Fitar](https://en.wikipedia.org/wiki/Eid_al-Fitr) Holidays - Staring from Wed 10 April 2024 (for 3 days). Please let me know if we need to fix those before? I will manage my time accordingly. 

Kind Regards,
Ali

2024-04-02 20:18 UTC, joedolson commented
No, there's no need to fix this faster than that. Thanks!

2024-04-10 20:29 UTC, alishanvr commented
@joedolson 

Please review when you get time. 

Thank You,

2024-04-24 19:48 UTC, joedolson commented
Hi, Ali! I'll get on this soon; been a hectic period, so I'm running slow.

2024-07-27 22:08 UTC, joedolson approved these changes

2024-07-27 22:10 UTC, joedolson commented
I'm going to make a few more changes, but I'm going to merge this as it is, and we can continue from there.

2024-07-27 22:10 UTC, merged